FROM centos:7

ENV VERSION=2.1.0-SNAPSHOT

ENV JAVA_HOME /usr/lib/jvm/java-openjdk

# Install Packages
RUN yum install -y java-1.8.0-openjdk-devel python2 curl vim sudo && \
    yum clean all

RUN ln -sf /usr/bin/python2 /usr/local/bin/python

COPY binaries/* /

RUN set -x \
    && cd / \
    && tar -xzvf apache-atlas-${VERSION}-bin.tar.gz

EXPOSE 21000

ENV PATH=$PATH:/apache-atlas-${VERSION}

ENV ATLAS_SERVER_HEAP="-Xms15360m -Xmx15360m -XX:MaxNewSize=5120m -XX:MetaspaceSize=100M -XX:MaxMetaspaceSize=512m"
# ENV ATLAS_SERVER_OPTS="-Djava.awt.headless=true -Djava.security.krb5.realm=SPYDER.COM -Djava.security.krb5.kdc=kdc"
ENV MANAGE_LOCAL_HBASE=false
ENV MANAGE_LOCAL_SOLR=true
ENV MANAGE_EMBEDDED_CASSANDRA=true
ENV MANAGE_LOCAL_ELASTICSEARCH=false

CMD ["/bin/bash", "-c", "/apache-atlas-${VERSION}/bin/atlas_start.py; tail -fF /apache-atlas-${VERSION}/logs/application.log"]
