version: "3"
services:
    ranger-db:
        image: spydernaz/apache-ranger-admin-db:latest
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=password
        depends_on:
            - "solr"
            - "atlas"
    apache-ranger:
        build: 
            context: ./apache-ranger
        stdin_open: true
        tty: true
        depends_on:
            - "ranger-db"
        ports:
            - "6080:6080"
    solr:
        image: 3962c880bda7
        ports:
            - "8983:8983"
            - "6083:6083"
        # command: solr start
        depends_on:
            - "atlas"
            - "zookeeper"
    atlas:
        image: mmiklas/atlas-docker:latest
        ports:
            - 21000:21000

    zookeeper:
        image: 'confluentinc/cp-zookeeper:5.0.0'
        environment:
            - ZOOKEEPER_CLIENT_PORT=2181
            - ALLOW_ANONYMOUS_LOGIN=yes
        depends_on:
            - atlas

    kafka:
        image: 'confluentinc/cp-kafka:5.0.0'
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper



