version: '3.7'
services:
    zookeeper:
        image: zookeeper:3.5
        container_name: zookeeper
        restart: always
        hostname: zookeeper
        ports:
            - 2181:2181
        environment:
            - ZOO_MY_ID=1
            - ZOO_SERVERS=server.1=0.0.0.0:2888:3888;2181
            - ZOO_4LW_COMMANDS_WHITELIST=*

    solr1:
        image: solr:8.3
        container_name: solr1
        ports:
            - "8981:8983"
        environment:
            - ZK_HOST=zookeeper:2181
        depends_on:
            - zookeeper

    solr2:
        image: solr:8.3
        container_name: solr2
        ports:
            - "8982:8983"
        environment:
            - ZK_HOST=zookeeper:2181
        depends_on:
            - zookeeper

    solr3:
        image: solr:8.3
        container_name: solr3
        ports:
            - "8983:8983"
        environment:
            - ZK_HOST=zookeeper:2181
        depends_on:
        - zookeeper

    upload_config:
        image: solr:8.3
        environment:
            - ZK_HOST=zookeeper:2181
        depends_on:
            - zookeeper
        volumes:
            - "./apache-ranger/ranger_audits/:/opt/solr-8.3.1/server/solr/configsets/ranger_audits/"
        command: bin/solr zk upconfig -n ranger_audits -d ranger_audits

    ranger-db:
        image: spydernaz/apache-ranger-admin-db:latest
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=password

    apache-ranger:
        image: spydernaz/apache-ranger-admin:experimental
        stdin_open: true
        tty: true
        depends_on:
            - "ranger-db"
        ports:
            - "6080:6080"