version: '3.7'
services:
    solr1:
        image: solr:8.3
        container_name: solr1
        ports:
            - "8981:8983"
        environment:
            - ZK_HOST=zoo1:2181
        depends_on:
            - zoo1

    solr2:
        image: solr:8.3
        container_name: solr2
        ports:
            - "8982:8983"
        environment:
            - ZK_HOST=zoo1:2181
        depends_on:
            - zoo1

    solr3:
        image: solr:8.3
        container_name: solr3
        ports:
            - "8983:8983"
        environment:
            - ZK_HOST=zoo1:2181
        depends_on:
        - zoo1

    zoo1:
        image: zookeeper:3.5
        container_name: zoo1
        restart: always
        hostname: zoo1
        ports:
            - 2181:2181
        environment:
            - ZOO_MY_ID=1
            - ZOO_SERVERS=server.1=0.0.0.0:2888:3888;2181

    atlas:
        image: 5b2973b00d43
        container_name: atlas-server
        restart: always
        ports:
            - 21000:21000